package com.sdase.malware.scanner.schedule;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.fail;
import static org.mockito.ArgumentMatchers.anyInt;
import static org.mockito.Mockito.doNothing;
import static org.mockito.Mockito.doThrow;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

import com.mongodb.MongoException;
import com.sdase.malware.scanner.service.CheckService;

@SpringBootTest
class ScheduledTaskTest {
	
	@MockBean
	private CheckService checkService;
	
	@Autowired
	private ScheduledTask scheduledTask;

	@Test
	void checkFilesSuccessTest() {
		doNothing().when(checkService).checkFiles(anyInt());
		try {
			scheduledTask.checkFiles();
		} catch(Exception e) {
			fail();
		}
	}
	
	@Test
	void checkFilesErrorTest() {
		doThrow(new MongoException("Error while connecting to the database")).when(checkService).checkFiles(anyInt());
		
		assertThrows(MongoException.class, () -> scheduledTask.checkFiles());
	}

}
